field: da4d3dd0-8d03-4b4b-a726-227e8e8b9f18
fieldLayouts:
  b03d1d39-d308-4147-b7dc-929a7406bade:
    tabs:
      -
        elements:
          -
            fieldUid: 852fecc5-c3e5-4ab0-8207-ff32a16a29fe
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1493fc20-82e0-4aab-a648-55f4208c7759
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 480522f0-91cb-4501-88bb-39a17496585d
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a86b255e-e2c4-401d-a832-0a4cb69ebf74
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1493fc20-82e0-4aab-a648-55f4208c7759:
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  480522f0-91cb-4501-88bb-39a17496585d:
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  852fecc5-c3e5-4ab0-8207-ff32a16a29fe:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a86b255e-e2c4-401d-a832-0a4cb69ebf74:
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: ''
    name: Phone
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: location
name: Location
sortOrder: 1
