fieldLayouts:
  69e08243-f8ad-475d-8044-2e04b0d7435c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: category
name: Category
siteSettings:
  3d5664b1-df6c-49fe-869f-1651fc217098:
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: f4ae6035-8a15-4d74-9f16-450109277273
