contentColumnType: string(400)
fieldGroup: e567cc2c-f882-4218-97fd-36b91ebc1e86
handle: blurb
instructions: ''
name: Blurb
searchable: true
settings:
  byteLimit: null
  charLimit: 100
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
