contentColumnType: string
fieldGroup: f81377fc-a458-47d8-81aa-a8d66f5e8dda
handle: image
instructions: ''
name: Image
searchable: true
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:0b2c024b-0d60-470c-9012-437ccf04d298'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0b2c024b-0d60-470c-9012-437ccf04d298'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
