contentColumnType: integer(10)
fieldGroup: 95b73f53-e7bb-4ff6-b6cb-d85ffbe03889
handle: price
instructions: ''
name: Price
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
