enableVersioning: false
handle: home
name: Home
propagationMethod: all
siteSettings:
  3d5664b1-df6c-49fe-869f-1651fc217098:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
