enableVersioning: false
handle: menuItems
name: 'Menu Items'
propagationMethod: all
siteSettings:
  3d5664b1-df6c-49fe-869f-1651fc217098:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
